In [1]:
import numpy as np
import random

In [2]:
np.sin

<ufunc 'sin'>

In [3]:
import numpy as np
x1= np.random.randint(0,10,10)
x2= np.random.randint(1,15,(3,4))
x3= np.random.randint(2,16,(4,4,5))

In [4]:
x1

array([9, 4, 5, 4, 0, 1, 1, 8, 1, 4])

In [5]:
x2

array([[10, 13, 14, 11],
       [ 6, 14,  6, 12],
       [10,  7,  3,  2]])

In [6]:
x3

array([[[ 5,  9,  9,  8,  2],
        [11, 12,  3, 13,  7],
        [10,  4,  5,  9, 13],
        [12,  2,  6, 15,  6]],

       [[ 7, 14, 10, 15, 14],
        [10, 14, 11,  9,  4],
        [ 3,  8,  8, 15, 14],
        [15,  6, 12,  2, 13]],

       [[11,  4,  7, 15, 14],
        [ 4, 14, 11,  8,  8],
        [ 5,  3,  3,  5, 13],
        [12,  8,  6,  8,  3]],

       [[11, 10,  6, 11,  5],
        [13,  8, 10,  2,  6],
        [ 9, 15, 10,  7,  2],
        [ 2,  2, 13, 11,  4]]])

In [7]:
x3.ndim

3

In [8]:
x2.shape

(3, 4)

In [9]:
x3.shape   # shapes shows your rows and column

(4, 4, 5)

In [10]:
x2.size # size gives total number of records

12

In [11]:
x3.size

80

In [12]:
x1.size

10

In [13]:
x1.itemsize

4

In [14]:
x2.itemsize

4

In [15]:
x3.itemsize

4

In [16]:
x1.nbytes
x2.nbytes
x3.nbytes
x1.nbytes

40

In [17]:
x2.nbytes

48

In [18]:
x3.nbytes # itemsize* size = nbytes

320

In [19]:
x1.dtype

dtype('int32')

In [20]:
x2.dtype

dtype('int32')

In [21]:
np.arange(1,45,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [22]:
x2

array([[10, 13, 14, 11],
       [ 6, 14,  6, 12],
       [10,  7,  3,  2]])

In [23]:
x2[2,2]=5
x2

array([[10, 13, 14, 11],
       [ 6, 14,  6, 12],
       [10,  7,  5,  2]])

In [24]:
t1=np.arange(2,19,3)
t1

array([ 2,  5,  8, 11, 14, 17])

In [25]:
t1.reshape(2,3)

array([[ 2,  5,  8],
       [11, 14, 17]])

In [26]:
t2=np.arange(1,40,2)
t2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [27]:
t2.reshape(5,4)

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31],
       [33, 35, 37, 39]])

In [28]:
t3=np.arange(2,20,2).reshape(3,3)
t3

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [29]:
t3.sum()

90

In [30]:
t3.sum(axis=0)

array([24, 30, 36])

In [31]:
t3.sum(axis=1)

array([12, 30, 48])

In [32]:
t1

array([ 2,  5,  8, 11, 14, 17])

In [33]:
t1.mean()

9.5

In [34]:
t1.transpose()


array([ 2,  5,  8, 11, 14, 17])

In [35]:
t1.var()

26.25

In [36]:
t1.std()

5.123475382979799

In [37]:
t1.prod(axis=0)

209440

In [38]:
import numpy as np
np.pi

3.141592653589793

In [39]:
s1=np.array([[1,2,3],
            [4,5,6]])
s1

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
s2=np.array([[3,3,4],
             [4,4,4]])
s2

array([[3, 3, 4],
       [4, 4, 4]])

In [41]:
w=np.concatenate([s1,s2],axis=0)
w

array([[1, 2, 3],
       [4, 5, 6],
       [3, 3, 4],
       [4, 4, 4]])

In [42]:
w=np.concatenate([s1,s2],axis=1)
w

array([[1, 2, 3, 3, 3, 4],
       [4, 5, 6, 4, 4, 4]])

In [43]:
w

array([[1, 2, 3, 3, 3, 4],
       [4, 5, 6, 4, 4, 4]])

In [45]:
w.hstack([s1,s2])

AttributeError: 'numpy.ndarray' object has no attribute 'hstack'

In [46]:
w.vsplit((2,3))

AttributeError: 'numpy.ndarray' object has no attribute 'vsplit'

In [47]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [50]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [51]:
np.random.randn(5,4).round(3)

array([[-0.333, -0.313, -0.018, -1.575],
       [-0.713, -0.792,  2.561,  0.246],
       [-0.203,  0.76 , -0.601,  0.545],
       [-0.143,  1.63 ,  1.462,  0.043],
       [-0.27 , -0.579, -0.172, -0.686]])

In [52]:
np.random.randn(3,3)

array([[-0.56253564,  0.0686963 ,  0.53958564],
       [-1.74821772,  0.2881727 , -0.18556402],
       [ 1.43789078,  0.05679777, -1.00239368]])

In [53]:
s1

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
s2

array([[3, 3, 4],
       [4, 4, 4]])

In [55]:
np.vstack((s1,s2))

array([[1, 2, 3],
       [4, 5, 6],
       [3, 3, 4],
       [4, 4, 4]])

In [56]:
np.hstack((s2,s1))

array([[3, 3, 4, 1, 2, 3],
       [4, 4, 4, 4, 5, 6]])

In [57]:
o=np.array([4,6,7,8,9,9])
o

array([4, 6, 7, 8, 9, 9])

In [58]:
p=np.split(o,2)
p

[array([4, 6, 7]), array([8, 9, 9])]

In [59]:
y=np.hsplit(o,2)
y

[array([4, 6, 7]), array([8, 9, 9])]

In [60]:
z=np.random.randint(3,9,(2,2))
z

array([[8, 5],
       [7, 7]])

In [61]:
t=np.vsplit(z,2)
t

[array([[8, 5]]), array([[7, 7]])]

In [62]:
z1=np.random.randint(3,6,(3,3))
z1

array([[5, 5, 5],
       [5, 5, 4],
       [5, 4, 4]])

In [63]:
t1=np.vsplit(z1,3)
t1

[array([[5, 5, 5]]), array([[5, 5, 4]]), array([[5, 4, 4]])]

In [64]:
#for loop and While loop

In [65]:
n= 'Priyan'
for i in n:
    print (i)


P
r
i
y
a
n


In [66]:
s={'c':'color','d':'dog','e':'elephant'}
for i in s.items():
    print(i[0],i[1])

c color
d dog
e elephant


In [67]:
for i in s.values():
    print(i)

color
dog
elephant


In [68]:
fruits=['apple','kiwi','papaya','melon']
fruits

['apple', 'kiwi', 'papaya', 'melon']

In [69]:
for i in enumerate(fruits):
    print(i)
    

(0, 'apple')
(1, 'kiwi')
(2, 'papaya')
(3, 'melon')


In [70]:
for i,j in enumerate(fruits):
    print(i,j)

0 apple
1 kiwi
2 papaya
3 melon


In [71]:
colors=('red','blue','green','yellow')
colors

('red', 'blue', 'green', 'yellow')

In [72]:
for i,j in enumerate(colors,start=12):
    print(i,j)

12 red
13 blue
14 green
15 yellow


In [73]:
s

{'c': 'color', 'd': 'dog', 'e': 'elephant'}

In [74]:
for i in s:
    print(i)

c
d
e


In [75]:
for i in s.values():
    print(i)

color
dog
elephant


In [76]:
for i in s.keys():
    print(i)

c
d
e


In [77]:
food =['biriyani','egg','karuvadu']
for i in enumerate(food):
    print(i)

(0, 'biriyani')
(1, 'egg')
(2, 'karuvadu')


In [78]:
# while loop

In [79]:
n1=[2,3,4,5,6,7]
while n1:
    print(n1.pop())

7
6
5
4
3
2


In [80]:
n1  # pop removes last element so in while loop it removes all t6he elements and here n1 remains empty

[]

In [81]:
i=1
while(i<12):
    print('priya')
    i+=2

priya
priya
priya
priya
priya
priya


In [82]:
t=0
while t<12:
    print('hello')
    t+=3
else:
    print('this is invalid')


hello
hello
hello
hello
this is invalid


In [83]:
i=0                     # average of 5 numbers
sum=0
while i<5:
    num=int(input())
    sum+=num
    i+=1
print(sum/5)

ValueError: invalid literal for int() with base 10: ''

In [84]:
h=np.random.randint(1,9,(3,4))
h

array([[5, 5, 7, 1],
       [7, 4, 5, 7],
       [7, 2, 1, 1]])

In [85]:
for i in h:
    print(i)

[5 5 7 1]
[7 4 5 7]
[7 2 1 1]


In [86]:
n5=np.random.randint(2,6,(3,4,3))
n5

array([[[4, 4, 2],
        [2, 2, 3],
        [4, 2, 3],
        [4, 2, 3]],

       [[5, 5, 3],
        [5, 3, 5],
        [2, 4, 3],
        [3, 3, 5]],

       [[2, 4, 4],
        [2, 5, 2],
        [5, 4, 3],
        [3, 4, 5]]])

In [87]:
for i in n5:
    for j in i:
        for k in j:
            print(k)
    

4
4
2
2
2
3
4
2
3
4
2
3
5
5
3
5
3
5
2
4
3
3
3
5
2
4
4
2
5
2
5
4
3
3
4
5


In [88]:
k

5

In [89]:
u=np.array([2,5,7,9])            #use np.ndenumerate for enumerating in numpy
for i in np.ndenumerate(u):
    print(i)

((0,), 2)
((1,), 5)
((2,), 7)
((3,), 9)


In [90]:
h=np.random.randint(2,9,(3,4))
h

array([[5, 4, 7, 8],
       [4, 2, 5, 3],
       [3, 4, 6, 8]])

In [91]:
for i in np.ndenumerate(h):
    print(i)


((0, 0), 5)
((0, 1), 4)
((0, 2), 7)
((0, 3), 8)
((1, 0), 4)
((1, 1), 2)
((1, 2), 5)
((1, 3), 3)
((2, 0), 3)
((2, 1), 4)
((2, 2), 6)
((2, 3), 8)


In [92]:
new_arr=([4,6,7,8,9])
k=np.array_split(new_arr,3)
k

[array([4, 6]), array([7, 8]), array([9])]

In [93]:
k[0]

array([4, 6])

In [94]:
new_arr

[4, 6, 7, 8, 9]

In [95]:
new_a=np.array([3,4,5,6,7,8])
# where is used to give the indexing part of an array, in this condition even number condition is aapplied
new1=np.where(new_a%2==0)
print(new1)


(array([1, 3, 5], dtype=int64),)


In [96]:
#searchsorted     is  also an indexing function
n2=np.array([2,3,4,5,6,7,8,9])
np.searchsorted(n2,5)


3

In [97]:
n3=np.array([1,3,4,5,7,8,'hi','hello','chennai'])
np.sort(n3)


array(['1', '3', '4', '5', '7', '8', 'chennai', 'hello', 'hi'],
      dtype='<U11')

In [98]:
arr=([40,41,42,43,44])
n1=[]
for i in arr:
    if i<=42:
        i='true'
        n1.append(i)
    else:
        i='false'
        n1.append(i)
        print(i)
        
    

false
false
